#+DATE: [2015-05-08 Fri] 
#+TITLE: 差错控制编码的说明
#+AUTHOR:    emacsun （所有文章遵循GPL协议）
#+EMAIL:     emacsun@163.com
#+DESCRIPTION: 差错控制编码的学习心得
#+KEYWORDS:  
#+TAGS:
#+CATEGORY: ECC
#+SETUPFILE: ~/.emacs.d/org-templates/level2.org 
#+LaTeX_CLASS: cn-article
       
* 动机

   长久以来，我都觉得差错控制编码教科书中的数学公式太多了。而且从一开始就太多了。很多人（包括我）刚开始的时候真的希望读读关于这些资料的科普性质的材料，就像读《大话移动通信》这样令人身心愉悦的读物一样。我不希望一开始就一大堆公式摆上来，我跟你又没有仇干嘛这样对我！我只想感性的，感！性！的！，了解一下信道编码到底是个什么东西。结果一上来就群环域，一上来就信息论，哪个受得了哦？就是吃酒席，还要先上开胃菜呢，对不对？所以我觉得世界上有必要出现一些针对差错控制编码的比较粗浅而又感性的文章，帮助大家建立差错控制编码的第一印象。这是我写这些博文的动机。
  
   我欢迎各行各业，五十六个民族，两百多个国家和地区的人们来阅读我的博文。如果你是一个理工科学生，那么读了这些博文足够让你忽悠你的女朋友（咳，咳，首先，你得。。。）；如果你是一个韩剧爱好者，那么读了这些博文足以证明你当初选错了专业。如果你是一个通信工程专业的本科生，读了这些博文，保证你想看看那些大部头的差错控制编码到底都tmd写了些啥东西；如果你是一个通信大牛，读了这些博文，就把那些有建设性的批评建议拍过来吧！求你了！保证让你拍的爽！反正就是我的这些博文啊，都是我一本参考书都不看就写出来的，保证是原汁原味的个人理解。买不了上当，买不了吃亏。

   有点张狂，原谅我少年的心，我这是第一次在网上吹牛B，反正也不报税的。我不止一次的看到高质量的博文（当然不是吹牛高质量），那博主写的举重若轻，鞭辟入里，读起来让人心旷神怡，如沐春风，仿佛文字都化作一把把按摩捶敲击我的每一个关节，爽啊爽啊啊啊啊啊。幻想有一天：俺也能写出如此博文，让读者也爽爽，这就是所谓的以飨读者啊！

* 我准备怎么做 
  <2015-05-09 Sat 21:35>

其实，用吹牛侃大山的风格介绍差错控制编码是有不少难度的。因为差错控制编码对数学的要求着实不低，从已经出版的专著上就可以看出来。但是如果我们跟着这些专著和那里的参考文献走，我们永远只能跟在别人后边，最多我们成为和他们一样的人，但是我们绝对不可能有那些大牛们的贡献大了。所以我决定，不跟他们走（虽然我已经跟了好久），我决定用自己的理解去阐述差错控制编码，我不想跟在他们后边，用那些佶屈聱牙的公式和文字折磨我的大脑和双眼。我要用通俗小说一样的文字去犒劳我这么久的学习。我的大脑厌倦了亦趋亦步，我的胃厌倦了别人嚼过的东西。是的，我决定自己嚼来吃。

怎么自己嚼？我的牙齿还不够锋利，我的大脑还不够睿智。不要紧，只要坚持下去，一定会形成自己的风格。就像同样的食材，不同的烹饪方式就会出现不同风味的佳肴一样。自己嚼也是对自己知识的一种梳理和检验。让我知道哪些东西是真正属于我自己的。哪些东西只不过是一种知识的记忆。

* 什么是差错控制编码 
  <2015-05-09 Sat 21:43>


啰里啰嗦一大堆，颇有一种鸡汤味儿。博主能不能告诉我tmd到底什么是差错控制编码吗?


