#+TITLE:   数学
#+AUTHOR:    emacsun
#+EMAIL:     emacsun@163.com
#+DATE:      
#+DESCRIPTION:  
#+KEYWORDS:  
#+CATEGORIES: 
#+SETUPFILE: ~/.emacs.d/org-templates/level1.org   
#+LaTeX_CLASS: cn-article  

* 引言 
  <2015-11-14 Sat 17:44> 

一个数学迷的数学笔记；

一个工科生的数学视角；

一个工程师的数学应用；

这是我的数学笔记，也是我为自己写的数学教科书。在完成这些博文的过程中，旁（dong）征（ping）博（xi）引（cou），不局限于某一本教材。虽有拾人牙慧之嫌，但是博文是理解相关知识点之后才写（chao）出来的，算是对教材作者的尊敬吧。在学习分析学的过程中，Water Rudin的三本分析杰作给了我很大的帮助。Rundin教授已经驾鹤西去，不知道他知道我把他的书抄的七零八散，会不会气的活过来。在学习线性代数和矩阵分析过程中，Gilbert Strang的MIT公开课让我受益匪浅(认真看了三遍教学视频，完成了作业)。其他数学方向的学习（组合数学，概率和随机过程）也参考了不少经典的资料。

我学数学全凭兴趣，用到再去学习。特别的，我对信道编码比较感兴趣。所以，目前为止，我的数学学习主要是离散的，倾向代数的。当然，由于通信工程的大背景，也学了一些分析方向的东西（比如，我啃完了Rudin的分析三部曲。）。从实用角度来讲，我会建议通信背景的学生多熟悉微积分这个工具，而不是去深入挖掘实数系是如何构建的。这些问题是数学专业的人来做得，他们帮我们构建数学大厦的基础，使得我们在实用数学工具的时候有底气，“瞧，我用的工具是有理论基础的。”。当然从提高自身的数学修养来讲，我建议多去读读分析学方面的杰作，像rudin，陶哲轩的分析学教材都很不错，对于提高自己的数学素养帮助很大。当然，这些严肃的分析学教材都是很烧脑很要时间的，常常让人怀疑自己的智商。但是，只要我们想到这些薄薄的教材是人类几百年的积淀，就会释然：我们还是站在巨人的肩膀上的。在短期内就要消化这么长时间的积淀，确实需要下一番功夫。

概率论和随机过程是通信专业必修课。甚至在学习信道编码的过程中，古典概型要更重要（就是那些让你数数的概率题）。在后来学习通信系统，信号处理的时候随机过程的作用开始显现，尤其统计信号处理非常重要。这些都离不开随机过程。

数学一直是通信工程师的短板（至少对我来说）。倘若立志在通信理论有所作为，数学素养恐怕要达到数学专业研究生的水平，甚至涉猎的方面要更广。总体而言，我学数学力求面广，具体学多深要看工作和学习中用到多少。所以我凭自己兴趣来，倒不觉得数学有多么难，也没有产生恨数学的想法。在不断的学习过程中，越来越领悟到：数学是给有耐心的人学的，学数学急不得。

我对数学的学习，从来不曾终止过。早期，由于学习方法不系统加上贪求过多，导致收效甚微。在阅读了不少关于学习方法以及人类思维意识方面的书籍之后，我决定逐点突破不再囫囵吞枣。我相信，当我积累到一定量之后，我所掌握的知识不再是一盘散沙，而会阡陌交通彼此互联。当然，投入大量时间是必须的。


* 数学分析
  [2016-03-27 Sun 19:45]

一直以为数学分析不就是baby rudin么？等到我真正读了baby rudin才明白，这个东西不是那么好懂。在学习的过程中，经常让我怀疑自己智商，怀疑人生。我的办法就是抄书。抄了一遍，习题有选择的做了一些，等到看第二遍的时候很多东西还是没有记住。又对照台湾交通大学的公开课（正好用的是rudin的那本书）学了一遍，算是对自己的分析之路有了交代。

现在，我会建议你：如果没有像我这么执拗，又不是必须要用，不要去学。青春，干什么不好，非要学数学。在学习的过程中，好几次都要放弃，但是每次看到那书放在桌子上，又有捡起来的冲动。记不得谁说的：如果你对一件事情多次放弃仍然有重头开始的热情，不如坚持下去，或许这个就是你的内心所向。我的数学分析之旅就是在这句话的激励下完成的，整体感觉还不错，在分析问题是感觉更加严密，很多东西不会想当然的认为。当然，在心理上也给了我莫大的安慰。

* 抽象代数 
  [2016-03-27 Sun 19:53]

抽象代数，我用的MIT Artin的教材，正好Harvard有公开课。学习策略和数学分析一样：抄书。相比分析，我更喜欢代数，可能是因为工作中研究信道编码的时候代数比分析用的更广。即使是我更喜欢代数，代数也没有因此变得简单。读完Artin的教材，跟完公开课，做了习题，也很要时间和精力。总之，学数学不是件容易的事情，甚至对于那些历史上的数学家而言，我想，如果不是因为有兴趣，他们也是学不下去的。但是兴趣这个东西是可以培养的，我对数学的兴趣是在抄书的过程中养成的。逐渐的，我发现抄书也不是那么枯燥无味。至少，在抄书的过程中，我发现数学原来是如此的严密简洁，高度抽象。在数学的世界里没有人情世故，对就是对，错就是错，马虎不得，更没有什么马屁可拍。

在学习抽象代数之前，我简略的把线性代数复习了一遍，主要教材是 Sheldon Axler 的 /Linear Algebra Done Right/ 这本书的第三版由人民邮电出版社引进，另外书后的习题有个专门的网站，[[http://linearalgebras.com/index.html][点这里]]。



* 具体数学
  [2016-03-27 Sun 20:00]

《具体数学》是计算机科学家Knuth的一本数学入门书，英文名字是《Concrete Mathematics》。书名中的Concrete是连续（continuous）和离散（district）的合写（当Knuth讲到这里的时候，那些建筑系搞混凝土的同学默默的离开了）。本书是理解Knuth《计算机程序设计与艺术》的数学预备。不是很难，读起来也饶有兴趣，至少比Rudin和Artin的书更有味道。本书对于做工程的学生更实用，几乎是读了就可以看到成效。



#+BEGIN_MAIN
     + [[file:./concreteMath/hanoi__toower.org][递归问题： 汉诺塔]]
     + [[file:./concreteMath/pizza.org][递归问题：瑞士披萨]]
     + [[file:./concreteMath/josephus.org][递归问题：约瑟夫问题]]
#+END_MAIN
