#+TITLE: 我的Tweet 
#+AUTHOR:    emacsun
#+EMAIL:     emacsun@163.com
#+DESCRIPTION: 
#+KEYWORDS:  
#+TAGS:
#+CATEGORY: 
#+SETUPFILE: ~/.emacs.d/org-templates/mytweet.org 
#+LaTeX_CLASS: cn-article


* 通信行业和互联网行业 
 [2017-02-17 Fri 20:11] 
 曾经，我认为我可以一直在通信行业做下去。入职H公司之后，经历了3GPP的推标过程，我才不情愿的发现通信早已是夕阳产业。在3GPP的会议上，各路诸侯为了那0.1dB的增益展开旷日持久的争斗。目前，香农极限已经逼近，管道流量已经足够。我觉得我们更应该关注管道中的内容。所以，私以为互联网行业是一个更开放的行业，尤其是基于无线网络和智能手机的互联网。无线互联网和智能手机是全人类的财富，在这个平台上机会源源不断的涌现。

* 关于未来的思考
  [2017-02-17 Fri 20:19]
  某公司最近的人清理，让我意识到必须保持身体健康和对新事物的好奇心，既要埋头苦干又要仰望星空。等温水烧热，即便想跳也只能心有余而力不足。
* 物联网：移动互联网的延续
  [2017-02-17 Fri 21:13]

  物联网是互联网发展的延续，爆发期预计在2018年底开始到2020这三年。下一代移动通信(5G)的一个重要特性就是万物互联，其标准预计会在2018年定型。准确的说，当前整个行业已经不是互联网阶段，而是进入了移动互联网发展的末期。那么再有1-2年左右，将正式进入物联网阶段。物联网不是一种技术，也不是什么标准，它更多的将是建立一种新的科技体系，以及以感知，云计算和大数据为核心的商业生态模型。物联网将彻底打破以计算机为终端的互联网时代，以及以智能手机为终端的移动互联网时代的单一载体为特征的网络架构和商业模式。 
* 以自身为中心的职业发展 
  [2017-03-18 Sat 09:42] 

  无论外汇，风向如何变化，始终保持一个开放的心态，终身学习的观念，才不至于痛苦。因为跳出舒适区是常有的事情，必须保证每一次跳出都发自内心，而不是处于被迫。要欢迎改变，稳定在这个时代是最不可能的事情。拥抱变化。
* 勇于跨越自己
  [2017-03-21 Tue 22:44] 

  那些跨出自己舒适区域的人，往往是人类中最勇敢最有创造力的人，比如当年从印度来到硅谷的科技人才，当年漂洋过海从欧洲来到澳洲的移民。那么我是不是也应该勇敢一下，从通信跨到互联网，再从互联网跨到金融。在这个跨越的过程中，保持一颗开放的心，就像旅行一样，看到的都是风景。
* 学习数学分析
  [2017-04-01 Sat 21:44]
  现在看来学好数学分析重在建立抽象概念，不断使用这个抽象概念建立第二本能。换句话说，我们不是学会了数学分析，而是适应了数学分析。另外数学分析中还需要记住一个个特例和反例，培养某种直觉。

* 做习题的重要性
  [2017-04-02 Sun 08:43]
  数学的习题是练习的机会，在练习的过程中学会用数学的语言解释问题。学习数学和学习语言的差别在于逻辑性。
