#+TITLE: 我为什么要写博客
#+AUTHOR:    emacsun
#+EMAIL:     emacsun@163.com
#+DESCRIPTION: 
#+KEYWORDS:  
#+TAGS:
#+CATEGORY: 
#+SETUPFILE: ~/.emacs.d/org-templates/level1.org 
#+LaTeX_CLASS: cn-article

* 早就想写
  <2015-07-18 Sat 02:36>

 大约大一的时候，第一次接触个人博客（我比较老土，高中之前基本没有接触过电脑）。那个时候觉得有个人博客的人都怎么这么牛，可以分享自己的东西给别人看，还能与全世界的人交流，草就在这个时候种下了。后来我接触了CSDN，cnblogs等网站，这些网站也可以托管博客，不用自己费神去搭建，试着写了一些，结果才发现胸无点墨，不好挥洒啊，写着写着就断了，敲着敲着就乱了。不知道到底写什么，二货的手指，写不出深刻的文字。但是那种交流和分享的欲望一直都在。

  至今，我已经工作了，有了一定经历和积淀，表达的愿望又日益强烈起来。是时候了，不能再以没有时间为借口拖延下去。于是我便开始了（才发现，工作了更没有时间，别理我，然我先哭一会儿）......

* 受别人的影响 
  <2015-07-18 Sat 09:54>

  我想写博客，我也去读了大量的别人的博客，收藏夹里也收藏了不少。其中促使我更坚定的写博客的一个博主是刘未鹏。读了他的 [[http://mindhacks.cn/2009/02/15/why-you-should-start-blogging-now/][《你为什么应该写博客》]] ，对我刺激很大（一万伏电压打击），觉得之前自己的生活杂乱无章，从没有下决心去整理。我有记日记的习惯，但在整理我的专业知识方面，却没有进展。我的知识库就像一片荒芜的草原，碎石乱地。我希望把它们修建成漂亮的花园，里面有整齐的草坪，清澈的河流和美丽的花圃。刘未鹏的那篇博文更坚定了我的信心。

  这里我把 [[http://mindhacks.cn/2009/02/15/why-you-should-start-blogging-now/][《你为什么应该写博客》]] 的要点掺和自己的感受总结一下，算是我写博客的原因，也算是几点读后感：
  + 能够交到很多志同道合的朋友。

一个长期的价值博客基本上就是个人生活的缩影，我是什么样的人，我的博客就会从不同方面展示出来，一篇，两篇，几百篇，每篇博文的文字都传达我性格的一个方面，长期下来，我的每一个方面都可以从我的博文中表达出来。最近我买了[[http://www.ruanyifeng.com/home.html][阮一峰]] 的《博客十年》，读下来感觉见证了一个优秀博主的十年成长史，就像结交了一个十年的老友。这种感觉是非常棒的。

博客以互联网为载体使得结交朋友变得更加容易。在互联网上你和任何人只有一个鼠标左键的距离，没有了地域的限制。更重要的是，你不需要重复的表达你的观点，因为你的观点都在博文里了。重复的表达自己的观点是令人讨厌的，我特别反感讲了一遍又一遍之后别人还忽闪着大眼睛问你“为什么”（也说明我不是一个很有耐心的人）。一片深思熟虑的博文不仅更完整的表达了我的观点，避免了遗漏，而且还避免了我重复的表达。就像java可以“一次编译，到处执行”，博客可以让我“一次编写，到处展示”。喜欢我博文的人会在我的博文里留言，有和我交流的愿望；不喜欢的则会默默的离开。博文也成了我交友的一个隐形的筛子，帮我过滤。爱屋及乌，"love me, love my blog"。总之，博客让交友变得更容易，免去我重复表达的口舌之苦并且让我更方便的择友。

  + 书写是为了更好的思考。 

刘未鹏在 [[http://mindhacks.cn/2009/02/09/writing-is-better-thinking/][《书写是为了更好的思考》]] 一文中阐述了书写的诸多好处。于我而言，我最深的体会是记日记给我带来的收获。一直我都有记生活日记的习惯，把我的“爱恨情仇”以及见不得人的想法和不能让某人知道的语言都付诸纸笔。当我翻看以前的日记时，就像发生的事情重新回放，我会思考如果再来，我会如何选择。看我的生活日记就好像读我自己的历史，培根说“读史可以使人明智”。以史为镜，鉴以往可以知未来。同样我的博文会促进我更好的思考。或许勤奋的你会发现，一件事情看上去很难，但是决定去做的时候也不过如此。

人们在做事情的时候容易犯两个错误：1）带着放大镜评估难易，2）完美主义，拖延着不肯去做。而事情一旦开头，做起来就很快了。写博文也是如此，刚开始的时候一篇博文只是一两句话和几个关键词。刘未鹏最开始在写 [[http://mindhacks.cn/2009/02/15/why-you-should-start-blogging-now/][《你为什么应该写博客》]] 时，只有三句话和十几个关键词，后来不断地发酵写成了那篇博文。我也有这样的感受，当我真正坐在屏幕前，碰上键盘时，就好像我的手指和键盘都会思考一样，看着我的思想从指间流向屏幕，这种感觉很棒的。

书写不仅促使我更好的思考，而且促使我更好的表达我的思想。有思想是一回事，把它表达出来又是一回事，把它精确的表达出来恐怕是一种境界了。尤其是理工男，在表达自己方面或多或少有一些欠缺，因为理工男都是问题解决型的人，擅长解决问题，而不是事后总结。很多时候，一个人不知道如何精确的表达自己所想，我知道这些文字也不能精确表达我的观点，但是书写促使我向精确的传达我的思想靠近。
  
  + 博客是一个有反馈的系统

与读者的交流是这个反馈系统的重要组成部分。交流促进更深入的思考，不断把你推向真理。交流更促使我反思自我，总有人和你观点不同，激烈的争辩让我更清晰的认识自己，这个世界上还有什么比“认识自己”更难的。实际上这个有反馈的系统带来上文的第2点。在不断反馈的过程中，“教学相长”。

在互联网上，遇到比自己懂得多的人不是什么稀奇。“是故无贵无贱，无长无少，道之所存，师之所存也”。当你真的可以把这个问题讲清楚，把这个故事讲圆了，你也就得到了它。在这个反馈系统的作用下，你的认识日以深刻，你开始变得更有思想。苏格拉底，柏拉图和亚里士多德都主张在讨论中发现问题，因为有讨论才有反馈，有反馈才有对已有观点的再次加工，再次思考。苏格拉底说“思想应当诞生在学生心里，教师仅仅应当像助产士那样办事”。是的，思想应该在每一个人的心里，一次高效而又深入的讨论应该像生产过程一样。

  + 博客让我可以专注的事情

我喜欢在安静的环境下，宅着写博客。听手指敲键盘的声音：键盘的每个区域都有自己的节奏和频率，空格和字母键都有自己的风格。在噼里啪啦的韵律中，我感觉整个人都要羽化了，好像这个键盘和屏幕是我手的延伸，有时候我要可以把手从键盘上拿开，因为我要确认它们是不是长在了键盘上。

能够专注做事情的人是幸福的，因为心无杂念。我在三件事情上可以做到专注：1）写博客，2）跑步。在做这些事情的时候，我不再无聊，不再迷茫。我知道我在做一件“没有明显坏处却有诸多好处的事情”。专注做事，提升我的定力，塑造我的性格，磨练我的心智。很幸运，我写博客和跑步的事情上找到了专注的感觉。哦，你说三件事情，怎么这里只有两件，第三件事情淡然是：爱老婆--在我的生活日记里，卿卿我我，你侬我侬。

  + 长期的坚持写博客等于不停的完善自己的简历

  这一点和第一点有点类似。你是什么样的人，就有什么样的简历，就会吸引什么样的朋友，这几乎是水到渠成的事情。我把我所掌握的专业技能亮出来，给别人看。这项技能不仅没有消失，反而变得更加光亮。我的潜在雇主很容易从我的博客上了解我是一个什么样的人。说不定，我自己雇用自己，这些博客也是对自己的交代。当某天，我审视自己的博文，内心一个声音告诉我“你可以自己雇佣自己了”，这也是对自己的肯定，对自己长期坚持的回报。

* 写作工具的发展 
  <2015-07-18 Sat 10:21>
  
工欲善其事必先利其器，此话不假。之前我也在CSDN和cnblogs上写过一些，后来全部删掉了。因为我不能让这个过程很流畅的完成，我必须去网页或者事先写好了粘贴上去，最要命的是我还要担心格式和排版是不是我想要的。这也是为什么我讨厌word，喜欢 \LaTeX 的原因。我只想在我的内容上花时间，不愿意浪费一秒钟在格式等无关的事情上。

直到有一天，我发现了Emacs和Org。Org不是一个独立的软件，它是Emacs的一个扩展。请记住：Org，你值得拥有。我用Org写博客，然后可以方便的导出为html，TeX, PDF，markdown等等格式，导出过程只需要按下对应的快捷键，一眨眼的功夫。

把博文从org文档生成html后，我需要管理我的博客系统，我使用github来记录博客的变迁，阮一峰有一篇文章： [[http://www.ruanyifeng.com/blog/2012/08/blogging_with_jekyll.html][如何使用github搭建免费博客]] 。参照这篇文章，我搭建了我的github静态博客。现在我用github托管我的博客，并且购买了github两年五个私有仓储的服务。github提供的服务足够我练手使用。

有了Emacs和github，我写博客就相当流畅：首先在Emacs里用Org写好org原始文档，然后自动发送到固定目录，接着使用git推送到github。从头到尾都没有离开Emacs，手指也没有离开键盘，我希望我自己是一只章鱼。

如果不想发表这篇博文，不推送到github即可，在本地也可以查看博客的草稿样子。使用Emacs可以控制firefox刷新网页，这样就不用去点到那个博文网页，再按F5。
  

最早有这个念头是看了刘未鹏的《你为什么应该写博客》 和他的《暗时间》，后来我又看了《程序员的思维训练》，发现我是倾向于以来文字来学习的学习者。我喜欢用笔和纸，用键盘来可视化我的想法。我不是那种上课可以不记笔记的人，这个对我来讲做不到。我喜欢写东西，然后回头看看当初幼稚的自己，并感慨自己的成长。另外Emacs为我记笔记提供了最得力的工具，尤其是其强大的扩展Org，让记笔记变成一种享受。

