#+TITLE:  设置cygwin和Emacs的语言环境
#+AUTHOR:    emacsun
#+EMAIL:     emacsun@163.com
#+DATE:      
#+DESCRIPTION:  总结了我使用Emacs做的事情
#+KEYWORDS:  
#+CATEGORIES: 
#+SETUPFILE: ~/.emacs.d/org-templates/level1.org
#+LaTeX_CLASS: cn-article

* 引言 
  <2015-08-30 Sun 07:42>

对于某些为别人打工的程序员（比如我）来说，想脱离windows完全使用linux显得有些不切实际，cygwin成了这些人的最后救赎。我使用cygwin和emacs，emacs不是cygwin里的emacs而是[[http://sourceforge.net/projects/emacsbinw64/][ 热心网友]] 编译的，我在Emacs里通过cygwin-mount使用cygwin的API。最近，我在使用cygwin时发现其gcc的报错输出变成中文了，本来GCC的报错格式就没有CLANG的好读，中文翻译一遍显得更不知所云。进而，我发现emacs的eshell里使用gcc报错输出也是中文。我要把这两个地方的报错提示改为英文。

* 解决方案
  <2015-08-30 Sun 07:50>

  办法比较简单，但是我还是折腾了一会儿才搞定。
** cygwin的shell中报错提示英文修改
   <2015-08-30 Sun 07:51>

   修改cygwin shell中的报错提示，只需要在 =~/.bashrc= 添加如下两行就可以。
#+begin_example 
export LANG='en_US'
export LC_ALL='en_US.UTF8'
#+end_example
** Emacs的eshell中报错提示英文修改
   <2015-08-30 Sun 07:57>

起初我以为只要cygwin中shell的报错提示英文化之后，Emacs中eshell的提示自然就会好起来，但是事实并不像我想象的这么简单。首先我修改了Emacs的语言环境：
#+begin_example 
(set-language-environment 'English)
#+end_example
然而，并不奏效。接着我又对那个 *compilation* buffer的编码系统（coding system）进行了修改，使用 =revert-buffer-with-coding-system= 命令把 *compilation* buffer 的编码变成GBK，然而这只是解决了乱码到正常显示中文，我要的是英文提示，修改文件编码并不能修改中英文显示问题。

最后，我想到了windows系统的控制面板里有 =区域和语言= 这一项。果然，通过修改windows 7的语言为英语，重启电脑，打开Emacs，进入eshell，键入gcc，看到了英文提示。打完收工。
