#+TITLE: 通信--数学与工程的完美结合
#+AUTHOR:    zcl.space
#+EMAIL:     emacsun@163.com
#+DESCRIPTION: 
#+KEYWORDS:  communication
#+TAGS: communication
#+CATEGORY: 
#+SETUPFILE: ~/.emacs.d/org-templates/level1.org
#+LaTeX_CLASS: cn-article
* 引言 
  <2015-11-14 Sat 16:48>

“烽火连三月，家书抵万金。”---杜甫《春望》

“此时相望不相闻，愿逐月华流照君”---张若虚《春江花月夜》

杜甫倘若能在烽火连三月发一条短信给家中妻儿一定欣喜若狂；张若虚倘若能与自己的爱人facetime，必定喜不自禁。 一千六百年后，通信工程正在以超乎想象的速度在这个蓝色星球催生翻天覆地的变化。我很高兴我是一名通信工程师，因为我参与其中：make the difference.


* 通信的开始
  <2015-11-14 Sat 14:28> 

通信从古至今都存在与人们的生活当中，或许这是人是群居动物的最佳佐证。从驿站到物流集散中心，从烽烟缆到光纤，通信的速度越来越快，然而不变的是信息的交流。最早的通信或许是原始智人打猎时的口哨声，或许是从这个山头到那个山头的呼喊。现代通信人们大都愿意从1905年马可尼发明跨大西洋电报系统算起。但我觉得现代通信更为恰当的起点是：麦克斯韦于1865年预言电磁波存在或者赫兹1888年证实电磁波的存在。从马可尼开始到1948年香农发表《通信的数学原理》一文，通信还都停留在混沌阶段。香农定义了信息的度量，开启了信息理论的新时代，通信人有了自己的理论基础。我觉得到1993年Turbo码的发明和LDPC码的重新发现，标志着现代通信理论到了一个阶段：AWGN下的通信系统性能距离香农极限只有0.0045dB。随后，新的技术比如massive MIMO和非正交接入技术流行，通信技术又以新的面孔示人。每一次通信系统的升级换代背后都包含着通信技术的革新。之所以通信技术会有如此迅速的发展，我觉得最重要的一点是：通信技术实现了与数学的完美结合，数学为通信技术提供理论支撑，通信工程又为数学提供新的问题，两者就像DNA的双螺旋结构一样，缺一不可。

* 我学通信
  <2015-11-14 Sat 14:56>

我学通信是从大学开始的，我只偶尔见过几次大哥大，第一个手机是诺基亚，这大概就是我学通信的背景。当时专业的名字叫做电子信息科学与技术。我的专业课与通信工程的专业课大同小异。《信号与系统》，《通信原理》，《信息论与编码》等等一门一门的学习，学完了毕业了大多东西都还给老师了。通信工程的本科生，编程搞不过学计算机的，算法搞不过学应用数学的，工程搞不过蓝翔技校毕业的。总之，通信工程专业就是个四不像专业。直到硕博毕业，才猛然发现，通信工程师是计算机，应用数学加蓝翔技校的毕业生都不如的，就因为我们有通信背景（我们是软件工程师里最懂通信的）。再后来，我也举一反三了一把：我是通信工程里搞算法最好的，我还是通信算法里最有工程经验的（请让我擦擦汗）。本科毕业之后，我仍然有好多东西不懂，也不急于找工作干脆再学学，把那些不懂的搞懂，死而无憾啊。从此，一入通信深似海，从此加班是常态。我觉得：我学通信能坚持下来，靠的是真爱（汗汗汗）。

* 我的通信教科书
  <2015-11-14 Sat 15:08>


  佛家有人生三重境界：“参禅之初，看山是山，看水是水；禅有悟时，看山不是山，看水不是水；禅中彻悟，看山仍是山，看水仍是水。”这三偈语颇富禅机，晦涩难解，却十分恰当地写出了人生随着阅历，年龄的增长对事物的看法所发生的变化。我学通信亦是如此。在本科理解的概念，到了读研究生的时候却觉得似懂非懂，如今工作了才发现还有如此玄机。通信，就是不停的学习，不停的领悟。

我看了不少书，甚至每一门课都看了不少同类的书。比如《信号与系统》我就把郑君里和奥本海默的都看了，并且认真完成了每一道习题，其他没有做题目的就不列举了。即便如此我对信号处理的卷积的概念还是在不停的演进，从最初的线性系统，到信号经历多径信道，然后信道均衡和信号复原（包括图像复原），卷积就像个幽灵一样无处不在。有时卷积简化了系统分析，比如对线性系统，给定输入，其输出就是系统响应和输入的卷积。有时卷积让问题变得复杂，比如经历信号多径信道是个卷积过程，在接收端为了恢复信号就要做类似反卷积的工作，这叫做均衡。《信号与系统》之后是《数字信号处理》。《信号与系统》侧重信号和系统的概念，大多从模拟信号讲起，而《数字信号处理》则着力数字信号。《信号与系统》和《数字信号处理》是通信与信息系统的基础（数学则是基础中的基础）。

在学习通信原理的时候，也参阅了不少教科书，北邮的，清华的，国外mit的，东北大学的，伯克利的等等等等。各有千秋，总体而言国内的太过浓缩，比较冷冰冰，国外的则比较活泼甚至有些啰嗦。一般我看国内的教材掌握龙脉，看国外的教材了解细节。国内的教材写的是知识，国外的教材写的是故事。国外教材印象比较深刻的是：proakis的《数字通信》，sklar的《数字通信基础》这几乎是通信工程学生必备了，后来接触了了伯克利大学Lee和Mwsserschmitt的《数字通信》和MIT Wozencraft和Jacobs的《通信工程原理》，到了研究生阶段又接触了stanford大学Goldensmith的《无线通信》，MIT Gallager《数字通信原理》和Tse的《无线通信基础》。几乎能在网上找到的全球知名院校的通信课堂材料，我都有电子档（感谢万能的互联网）。诸多教材当然不可能一本借一本开下去，会成书呆子的。认真读的有proakis的《数字通信》，仔细做了课后习题，算是指引我入了通信的门。比较推崇的是Wozencraft和Jacobs的《通信工程原理》。虽然有些老，但这本书里把信号的几何表示写的最好，后来的教科书几乎都延续了这种风格。Gallager的《数字通信原理》讲的最深入(在MIT的OCW网站上有gallager的公开课)，其徒弟Lapidoth的《a foundation of digital communication》与其一脉相承。David Tse的《无线通信基础》可以说把通信工程和通信算法结合的最好，而且花费大量篇幅阐述MIMO的分集复用原理，并与当前商用的通信系统紧密结合，前后翻了好几遍，但是并没有抽出时间去做大量的习题，算是一个遗憾。


信息论与编码这门课还是有些难度的，我当时的教材是《信息论与编码》，中科大出的研究生教材，作者是姜丹。很荣幸，授课老师也是姜丹。老教授把晦涩难懂的编码知识讲的浅显易懂，而且全程板书，上课不带教材。我这门课的笔记做的也最认真，都不敢相信自己还有这么有条理的笔记。当然，课堂上老师只会讲解大概，修炼还要靠个人。对Turbo编码了LDPC编码的深入理解，我是通过《差错控制编码》来完成的。《差错控制编码》作者是林纾，台湾人。这本书蜚声国内外，讲解也比较仔细，亚马逊上很多歪果仁对此评价颇高，国人高编码的更几乎是人手一本了。后来林纾又出了一本书《channel coding》还没有翻译版，主要讲解Turbo和LDPC，很不错。整个编码理论的发展可以说经历两条主线：分组码和卷积码。分组码一诞生就基于抽象代数，具有严密的逻辑基础，推导而来。卷积码的发展就没有那么顺利，Elias发明卷积码之后，Viterbi提出了Viterbi算法，Forney证明Viterbi算法是一种ML算法，都不是一个人完成的。所以信道编码发展的初期阶段又很多介绍编码的书籍都限于分组码。但是，卷积码更好的性能吸引着人们寻找理论框架去解释这种编码方式。Turbo码诞生之后，由于在编码过程中引入交织，其理论解释更为困难。Berrou等人发明Turbo码的时候没有为其做理论分析，以至于人们根本不敢相信这三个做电路的人（两个教授，一个博士生）竟能做出性能如此好的编码，纷纷猜测是不是犯了3dB的错误。无论是分组码和卷积码，到目前为止都被统一到基于因子图的编码，其译码都可以采用一种叫做消息传递算法（Message Passing Algorithm）的算法。至此，信道编码领域算是实现了大一统。而且Forney等人做出了距离香农极限0.0045dB的LDPC码，码块长度是 \(10^{7}\)。虽然，之后又诞生了turbo乘积码（TPC）和rateless码（喷泉码），但是Turbo码和LDPC码之后的编码届都在做性能和复杂度的折中。

* 博客：我自己的教科书
  <2015-11-14 Sat 16:30>

看的多了就有要表达的意愿，希望与人分享大彻大悟的感觉。学了这么久，的确也会有一些茅塞顿开的时刻。我想把自己的领悟过程记录下来，以备以后重新查看，所以我记录了不少笔记。后来，我又想把自己的这些东西整理一下分享被别人，所以建了这个博客（我用Emacs完成了这个小站的所有工作，如何用Emacs建立静态网站不在本文范围之内，请问度娘和谷哥）。

我希望为自己写教科书，用自己喜欢的语言和次序。虽然这里的大多数内容来自于众多教科书，但是整理的过程又是一次理解的过程，在写作的过程中又是一次巩固的过程。

在写作的过程中，整个过程为：打开电脑，打开Emacs，把手放在键盘上，奔跑吧。我喜欢编写边听音乐，最喜欢古典音乐：莫扎特的童趣，巴赫的庄严，肖邦的忧伤流入我的耳朵，流向我的指尖和通信数学计算机（我博文的三大块：通信，数学，计算机）一起混响。写博文给了我不同的体验，前所未有的专注和内省。后来我又喜欢在写博客的敲键盘的时候听maksim，不得了了，老婆问我为什么敲着键盘还在抖腿，不要问我，扶我起来，看看我的膝盖还在不在。maksim的《野蜂群舞》《出埃及记》应该是键盘工作者的最爱，无与伦比的速度绝对销魂。现在唯一的遗憾是没有从大学开始就写博客。如果那时开始，估计也《博客十年》了。

我写博客，首先读者是我自己，不保证博文内容妇孺皆知，但是尽量深入浅出。如果你看了之后一头雾水，正常，我不是为你而写。因为我本来就是一个比较奇特的人，别的不说，单单是最Emacs的热情，我的朋友圈里除了我没别人了。当然，我也不是冷酷无情的“鳄鱼”，如果你想和我交流，请给我留言，我非常欢迎的。毕竟，公开这些博文的目的之一也是为了和同好一起探讨。
* 尾声 
  <2015-11-14 Sat 16:48>

啰里啰嗦这么多，满纸荒唐言，一把通信泪。喜欢通信，喜欢数学与工程的完美结合。
